#!/usr/bin/env bash
#Display story with each line of /etc/passwd
file="/etc/passwd"
while IFS=: read -r g1 g2 g3 g4 g5 g5 g6 g7
do
	echo "The user $g1 is part of the $g4 gang, lives in $g6 and rides $g7. $g3's place is protected by the passcode $g2, more info about the user here: $g5"
done
