#!/usr/bin/env bash
# This script uses case statement
c=1
while [ $c -le 20 ]
do
	echo "$c"
	case $c in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((c++))	
done
