#!/usr/bin/env bash
#Script uses nested loops to display the time for 12 hours and 59 minutes
hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minutes=1
	while [ $minutes -lt 60 ]
	do
		echo "$minutes"
		((minutes++))
	done
	((hour++))
done
