#!/usr/bin/env bash
# Script configures an Ubuntu server
cp /etc/hosts ~/hosts.new
sed -i 's/.*localhost/127.0.0.2 localhost/g' ~/hosts.new
sed -i 's/.*facebook.com//g' ~/hosts.new
sed -i 's/.*facebook.com//g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
